MoneyApp_KerimZuna
KerimZuna/MoneyApp pull request #1
Opened 2023-08-01 08:07 UTC by KerimZuna

Poštovanje, 

šaljem Vam PR kako bih odradili review za testnu 'MoneyApp' aplikaciju. Sve je bilo commit-ano na main branch, jer nisam do sada koristio Pull Request. Zato je trenutno samo ova jedna izmjena napravljena kako bih mogao poslati PR. Hvala unaprijed.

S poštovanjem,
Kerim Žuna.

2023-08-01 13:39 UTC, esuljic commented
I moved main base to the first commit, so all the commits now are in this PR and I can review them. Usually, all the communication in the GitHub is done in English. I hope that is not a problem.

2023-08-01 13:47 UTC, esuljic requested changes

2023-08-01 13:47 UTC, esuljic commented on money_app/lib/controllers/loanController.dart
> +  RxBool acceptedTerms = false.obs;
All Rx variables needs to be final.

2023-08-01 13:47 UTC, esuljic commented on money_app/lib/models/modelTransaction.dart
> +class Transakcije {
Model names are always written in singular

2023-08-01 13:47 UTC, esuljic commented on money_app/lib/models/modelTransaction.dart
> +class Transakcije {
The filename `modelTransaction.dart` is not good. It should be just `transaction.dart`.

2023-08-01 13:47 UTC, esuljic commented on money_app/lib/loan.dart
> +  Widget build(BuildContext context) {
Please refactor the project so that it uses [get_cli](https://pub.dev/packages/get_cli). Recreate all the pages with `get create page:<pageName>`. Every page should have their controller. All the logic should be in the controller, and all of the UI should be in the view classes.

2023-08-07 10:30 UTC, KerimZuna commented
Hello Enver,

I have made the requested changes, besides the last one (refactor the
project to use get_cli). I have a problem with setting up get_cli.
Issue: First I attempted to add get_cli: ^1.8.1 to the pubspec.yaml
dependencies and run flutter pub upgrade. This resulted in conflicts with
dependencies. The solution I found was to switch the flutter channel to
master. This solved the conflicted dependencies and get_cli was ready to
use. First command that I have tried is: flutter pub global run get_cli
create (found on StackOverflow while trying to fix the dependency issue )
to create the project. This resulted in the following error (Could not find
bin/get_cli.dart in package get_cli). Since I am using Ubuntu, I looked up
the solutions on StackOverflow (solution
<https://stackoverflow.com/questions/52794266/pub-global-activate-command-home-pub-cache-bin-not-on-path>).
Unfortunately, this did not fix the issue. Since I have noticed that the
commands to actually run the project on the official get_cli
<https://pub.dev/packages/get_cli> documentation were not the same as the
ones I found on StackOverflow, I decided to try and create a project using
the following command - get create project. This created the project itself
but an error came up in the process (error_unexpected ShellException(dart
migrate --apply-changes --skip-import-check, exitCode 64, workingDirectory:
/home/nazezu/Desktop/MoneyApp/money_app/money_app). Since it was able to
create the project, but the project was empty, I assume that it tried to
migrate all of my files to the newly created get project and for some
reason failed. I have drained most of the resources that were available to
my knowledge to try and fix this issue before I contacted you, since
troubleshooting is the best way to figure things out. But I do not want to
drag this test application for too long so I am asking you to please help
me to figure this issue out. Could it be an Ubuntu related problem?

Thank you in advance.

Sincerely, Kerim Žuna.


uto, 1. kol 2023. u 15:39 Enver Suljic ***@***.***> napisao
je:

> I moved main base to the first commit, so all the commits now are in this
> PR and I can review them. Usually, all the communication in the GitHub is
> done in English. I hope that is not a problem.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KerimZuna/MoneyApp/pull/1#issuecomment-1660353310>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUOGPQO7VIYFXLXMBOY7YDDXTEBINANCNFSM6AAAAAA27LTQEU>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-09 09:40 UTC, KerimZuna commented
Hello Enver, I have managed to setup get_cli and I will be refactoring my project according to your requested changes.

2023-08-09 10:17 UTC, KerimZuna commented
I need an advice. Should I a) Create a get project inside this project with a GetX template and then refactor my code and copy it into this new project or b) Just modify my existing files without the use of the GetX template even though the file structure may not be 100% accurate?

2023-08-09 12:09 UTC, esuljic commented
> I need an advice. Should I a) Create a get project inside this project with a GetX template and then refactor my code and copy it into this new project or b) Just modify my existing files without the use of the GetX template even though the file structure may not be 100% accurate?

Just create screen by screen, for example `main`, that will create new `modules/main/` with `views`, `controllers` and `bindings` inside. Then move all the logic from your current files to those. After that, remove the old files. Do this for all the screens,

2023-08-09 12:09 UTC, esuljic requested changes

2023-08-09 12:09 UTC, esuljic commented on money_app/lib/controllers/balance_controller.dart
> +class AmountController extends GetxController {
File name is `balance_controller.dart`, class name is `AmountController`, they need to be synced.

2023-08-09 12:09 UTC, esuljic commented on money_app/lib/details_transaction.dart
> +        final RxString decimals = (balance % 1).toStringAsFixed(2).substring(1).obs;
Creating `Rx` variables (putting `.obs`) inside `Obx` doesn't make sense. Everytime `Obx` rebuilds, new `Rx` variables are created, which means that the `Obx` is not updated as the old `Rx` variable is never updated.

2023-08-09 12:09 UTC, esuljic commented on money_app/lib/models/transaction.dart
> +enum  TypeOfTransaction{
Should be named `TransactionType`

2023-08-11 09:54 UTC, KerimZuna commented
Couple of UI elements have changed their appearance since I refactored my project, for example the back button changed it's color to black, the elevated button has a border radius. How do I change those if they are not defined anywhere in the code?

2023-08-14 08:47 UTC, esuljic requested changes

2023-08-14 08:47 UTC, esuljic commented on money_app/lib/app/modules/DetailsTransaction/views/details_transaction_view.dart
>        body: Obx(() {
Do you need `Obx` here, do you user any Rx variable inside?

2023-08-14 08:47 UTC, esuljic commented on money_app/lib/app/modules/Home/views/home_view.dart
> +                      final balance = Get.find<HomeController>().amount.value;
Instead of `Get.find<HomeController>()` everytime, just type `controller`. `HomeView` extends `GetView<HomeController>` so it is available already.

2023-08-16 18:54 UTC, esuljic requested changes

2023-08-16 18:54 UTC, esuljic commented on money_app/lib/app/modules/DetailsTransaction/bindings/details_transaction_binding.dart
> +class DetailsTransactionBinding extends Bindings {
All of the modules are named with CapitalCamelCase instead of snake_case

2023-08-16 21:52 UTC, KerimZuna commented on money_app/lib/app/modules/DetailsTransaction/bindings/details_transaction_binding.dart
> +class DetailsTransactionBinding extends Bindings {
I have only changed the name of the folder for every module. Class names stay the same because it recommends CapitalCamelCase for class names.

2023-08-30 13:55 UTC, merged